# Generated by Django 4.1.3 on 2022-12-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_egresados_profesores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresados',
            old_name='Diploma',
            new_name='titulo',
        ),
    ]
