# Generated by Django 4.1.3 on 2022-12-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_egresado_egresados_egresado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresados',
            old_name='egresado',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='egresados',
            old_name='titulo',
            new_name='titulacion',
        ),
    ]
